name: frog_demo
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation:
  logger: ^2.0.2+1
  uuid: ^4.3.3

dev_dependencies:
  build_runner:
  json_serializable:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
